var app = angular.module('myApp', []);

app.controller('MainCtrl', function($scope) {

    $scope.currentView = "overall";

    $scope.selectView = function(view) {
        $scope.currentView = view;
    };

    $scope.getPlayerName = function(id) {
        var displayname = "";

        for(var player of $scope.roster) {
            if (player.id == id){
                displayname = displayname + player.firstname;
                if (player.nickname != ""){
                    displayname = displayname + " '" + player.nickname + "' ";
                }
                displayname = displayname + " " + player.lastname;
            }
        }
        return displayname;
    };


    $scope.roster2015 = [
        {
            "id":2,
            "type": "player",
            "firstname": "catelen",
            "lastname": "ramsey",
            "nickname": "rams",
            "image": "img/Roster2015/Roster_Rams.jpg"
        },
        {
            "id":3,
            "type": "player",
            "firstname": "alaine",
            "lastname": "wetli",
            "nickname": "shakes",
            "image": "img/Roster2015/Roster_Shakes.jpg",
        },
        {
            "id":4,
            "type": "player",
            "firstname": "sarah",
            "lastname": "butts",
            "nickname": "",
            "image": "img/Roster2015/Roster_Butts.jpg",
        },
        {
            "id":5,
            "type": "player",
            "firstname": "stevie",
            "lastname": "miller",
            "nickname": "",
            "image": "img/Roster2015/Roster_Stevie.jpg",
        },
        {
            "id":6,
            "type": "player",
            "firstname": "corinn",
            "lastname": "pruitt",
            "nickname": "champ",
            "image": "mg/Roster2015/Roster_Blank.jpg",
        },
        {
            "id":8,
            "type": "player",
            "firstname": "becky",
            "lastname": "moore",
            "nickname": "tots",
            "image": "img/Roster2015/Roster_Tots.jpg",
        },
        {
            "id":9,
            "type": "player",
            "firstname": "janine",
            "lastname": "walker",
            "nickname": "",
            "image": "img/Roster2015/Roster_Janine.jpg",
        },
        {
            "id":10,
            "type": "player",
            "firstname": "kristen",
            "lastname": "smiach",
            "nickname": "",
            "image": "img/Roster2015/Roster_Kristen.jpg",
        },
        {
            "id":11,
            "type": "player",
            "firstname": "tracey",
            "lastname": "lo",
            "nickname": "t-lo",
            "image": "img/Roster2015/Roster_TLo.jpg",
        },
        {
            "id":12,
            "type": "player",
            "firstname": "katie",
            "lastname": "backus",
            "nickname": "zeus",
            "image": "img/Roster2015/Roster_Zeus.jpg",
        },
        {
            "id":14,
            "type": "player",
            "firstname": "theresa",
            "lastname": "zettner",
            "nickname": "tz",
            "image": "img/Roster2015/Roster_TZ.jpg",
        },
        {
            "id":15,
            "type": "player",
            "firstname": "daniela",
            "lastname": "bova",
            "nickname": "",
            "image": "img/Roster2015/Roster_Blank.jpg",
        },
        {
            "id":16,
            "type": "player",
            "firstname": "sarah",
            "lastname": "craycraft",
            "nickname": "jules",
            "image": "img/Roster2015/Roster_Jules.jpg",
        },
        {
            "id":17,
            "type": "player",
            "firstname": "lauren",
            "lastname": "franke",
            "nickname": "",
            "image": "img/Roster2015/Roster_Franke.jpg",
        },
        {
            "id":18,
            "type": "player",
            "firstname": "caitlin",
            "lastname": "harley",
            "nickname": "",
            "image": "img/Roster2015/Roster_Blank.jpg",
        },
        {
            "id":20,
            "type": "player",
            "firstname": "julia",
            "lastname": "weinert",
            "nickname": "",
            "image": "img/Roster2015/Roster_Blank.jpg",
        },
        {
            "id":21,
            "type": "player",
            "firstname": "mary",
            "lastname": "turner",
            "nickname": "",
            "image": "img/Roster2015/Roster_Mary.jpg",
        },
        {
            "id":22,
            "type": "player",
            "firstname": "kristi",
            "lastname": "steva",
            "nickname": "cheme",
            "image": "img/Roster2015/Roster_Cheme.jpg",
        },
        {
            "id":27,
            "type": "player",
            "firstname": "bailey",
            "lastname": "torvinen",
            "nickname": "",
            "image": "img/Roster2015/Roster_Bailey.jpg",
        },
        {
            "id":31,
            "type": "player",
            "firstname": "sara",
            "lastname": "scott",
            "nickname": "",
            "image": "img/Roster2015/Roster_Sara.jpg",
        },
        {
            "id":33,
            "type": "player",
            "firstname": "isabel",
            "lastname": "simon",
            "nickname": "is",
            "image": "img/Roster2015/Roster_Isabel.jpg",
        },
        {
            "id":37,
            "type": "player",
            "firstname": "hannah",
            "lastname": "henkin",
            "nickname": "hank",
            "image": "img/Roster2015/Roster_Hannah.jpg",
        },
        {
            "id":400,
            "type": "coach",
            "firstname": "deanna",
            "lastname": "ball",
            "nickname": "",
            "image": "img/Roster2015/Roster_Deanna.jpg",
        },
        {
            "id":401,
            "type": "coach",
            "firstname": "andy",
            "lastname": "theiss",
            "nickname": "",
            "image": "img/Roster2015/Roster_Theiss.jpg",
        }
    ];

  $scope.roster2016 = [
      {
          "id":1,
          "type": "player",
          "firstname": "sadie",
          "lastname": "jezierski",
          "nickname": "",
          "image": "user_sadie.jpg",
          "imageff": "ff_sadie.jpg",
      },
      {
          "id":2,
          "type": "player",
          "firstname": "ashley",
          "lastname": "leyden",
          "nickname": "",
          "image": "user_ashley.jpg",
          "imageff": "ff_ashley.jpg",
      },
      {
          "id":3,
          "type": "player",
          "firstname": "alaine",
          "lastname": "wetli",
          "nickname": "shakes",
          "image": "user_shakes.jpg",
          "imageff": "ff_shakes.jpg",
      },
      {
          "id":4,
          "type": "player",
          "firstname": "sarah",
          "lastname": "butts",
          "nickname": "rocket",
          "image": "user_butts.jpg",
          "imageff": "ff_butts.jpg",
      },
      {
          "id":5,
          "type": "player",
          "firstname": "stevie",
          "lastname": "miller",
          "nickname": "",
          "image": "user_stevie.jpg",
          "imageff": "ff_stevie.jpg",
      },
      {
          "id":6,
          "type": "player",
          "firstname": "corinn",
          "lastname": "pruitt",
          "nickname": "champ",
          "image": "user_champ.jpg",
          "imageff": "ff_champ.jpg",
      },
      {
          "id":8,
          "type": "player",
          "firstname": "becky",
          "lastname": "moore",
          "nickname": "tots",
          "image": "user_tots.jpg",
          "imageff": "ff_tots.jpg",
      },
      {
          "id":9,
          "type": "player",
          "firstname": "janine",
          "lastname": "walker",
          "nickname": "",
          "image": "user_janine.jpg",
          "imageff": "user_janine.jpg",
      },
      {
          "id":10,
          "type": "player",
          "firstname": "kristen",
          "lastname": "smiach",
          "nickname": "",
          "image": "user_kristen.jpg",
          "imageff": "ff_kristen.jpg",
      },
      {
          "id":11,
          "type": "player",
          "firstname": "tracey",
          "lastname": "lo",
          "nickname": "t-lo",
          "image": "user_tlo.jpg",
          "imageff": "user_tlo.jpg",
      },
      {
          "id":12,
          "type": "player",
          "firstname": "katie",
          "lastname": "backus",
          "nickname": "zeus",
          "image": "user_zeus.jpg",
          "imageff": "ff_zeus.jpg",
      },
      {
          "id":14,
          "type": "player",
          "firstname": "theresa",
          "lastname": "zettner",
          "nickname": "tz",
          "image": "user_tz.jpg",
          "imageff": "ff_tz.jpg",
      },
      {
          "id":15,
          "type": "player",
          "firstname": "brittany",
          "lastname": "wright",
          "nickname": "",
          "image": "user_brittany.jpg",
          "imageff": "ff_brittany.jpg",
      },
      {
          "id":16,
          "type": "player",
          "firstname": "sarah",
          "lastname": "craycraft",
          "nickname": "jules",
          "image": "user_jules.jpg",
          "imageff": "ff_jules.jpg",
      },
      {
          "id":18,
          "type": "player",
          "firstname": "caitlin",
          "lastname": "harley",
          "nickname": "",
          "image": "user_harley.jpg",
          "imageff": "ff_harley.jpg",
      },
      {
          "id":20,
          "type": "player",
          "firstname": "sophie",
          "lastname": "knowles",
          "nickname": "",
          "image": "user_sophie.jpg",
          "imageff": "ff_sophie.jpg",
      },
      {
          "id":21,
          "type": "player",
          "firstname": "dani",
          "lastname": "runzo",
          "nickname": "",
          "image": "user_dani.jpg",
          "imageff": "ff_dani.jpg",
      },
      {
          "id":22,
          "type": "player",
          "firstname": "talia",
          "lastname": "barth",
          "nickname": "",
          "image": "user_talia.jpg",
          "imageff": "ff_talia.jpg",
      },
      {
          "id":27,
          "type": "player",
          "firstname": "bailey",
          "lastname": "torvinen",
          "nickname": "",
          "image": "user_bailey.jpg",
          "imageff": "ff_bailey.jpg",

      },
      {
          "id":28,
          "type": "player",
          "firstname": "lauren",
          "lastname": "ficek",
          "nickname": "monty",
          "image": "user_monty.jpg",
          "imageff": "user_monty.jpg",
      },
      {
          "id":30,
          "type": "player",
          "firstname": "jodi",
          "lastname": "mcCloskey",
          "nickname": "",
          "image": "user_jodi.jpg",
          "imageff": "user_jodi.jpg",
      },
      {
          "id":31,
          "type": "player",
          "firstname": "sara",
          "lastname": "scott",
          "nickname": "",
          "image": "user_sarascott.jpg",
          "imageff": "ff_sarascott.jpg",
      },
      {
          "id":37,
          "type": "player",
          "firstname": "hannah",
          "lastname": "henkin",
          "nickname": "hank",
          "image": "user_hank.jpg",
          "imageff": "ff_hank.jpg",
      },
      {
          "id":77,
          "type": "player",
          "firstname": "amanda",
          "lastname": "noonan",
          "nickname": "",
          "image": "user_amanda.jpg",
          "imageff": "ff_amanda.jpg",
      },
      {
          "id":400,
          "type": "coach",
          "firstname": "deAnna",
          "lastname": "ball",
          "nickname": "",
          "image": "user_deanna.jpg",
          "imageff": "user_deanna.jpg",
      },
      {
          "id":401,
          "type": "coach",
          "firstname": "andy",
          "lastname": "theiss",
          "nickname": "",
          "image": "user_theiss.jpg",
          "imageff": "user_theiss.jpg",
      }
  ];

      $scope.roster = $scope.roster2016;

});
